// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConfigInitParameters struct {

	// (Boolean) Whether or not the Doppler config can be inherited by other configs
	// Whether or not the Doppler config can be inherited by other configs
	Inheritable *bool `json:"inheritable,omitempty" tf:"inheritable,omitempty"`

	// (List of String) A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler_config resource (e.g. doppler_config.backend_stg.descriptor)
	// A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler_config resource (e.g. doppler_config.backend_stg.descriptor)
	Inherits []*string `json:"inherits,omitempty" tf:"inherits,omitempty"`
}

type ConfigObservation struct {

	// (String) The descriptor (project.config) of the Doppler config
	// The descriptor (project.config) of the Doppler config
	Descriptor *string `json:"descriptor,omitempty" tf:"descriptor,omitempty"`

	// (String) The name of the Doppler environment where the config is located
	// The name of the Doppler environment where the config is located
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether or not the Doppler config can be inherited by other configs
	// Whether or not the Doppler config can be inherited by other configs
	Inheritable *bool `json:"inheritable,omitempty" tf:"inheritable,omitempty"`

	// (List of String) A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler_config resource (e.g. doppler_config.backend_stg.descriptor)
	// A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler_config resource (e.g. doppler_config.backend_stg.descriptor)
	Inherits []*string `json:"inherits,omitempty" tf:"inherits,omitempty"`

	// (String) The name of the Doppler project where the config is located
	// The name of the Doppler project where the config is located
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type ConfigParameters struct {

	// (String) The name of the Doppler environment where the config is located
	// The name of the Doppler environment where the config is located
	// +crossplane:generate:reference:type=github.com/oxlev/provider-doppler/apis/namespaced/secrets/v1alpha1.Environment
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// Reference to a Environment in secrets to populate environment.
	// +kubebuilder:validation:Optional
	EnvironmentRef *v2.NamespacedReference `json:"environmentRef,omitempty" tf:"-"`

	// Selector for a Environment in secrets to populate environment.
	// +kubebuilder:validation:Optional
	EnvironmentSelector *v2.NamespacedSelector `json:"environmentSelector,omitempty" tf:"-"`

	// (Boolean) Whether or not the Doppler config can be inherited by other configs
	// Whether or not the Doppler config can be inherited by other configs
	// +kubebuilder:validation:Optional
	Inheritable *bool `json:"inheritable,omitempty" tf:"inheritable,omitempty"`

	// (List of String) A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler_config resource (e.g. doppler_config.backend_stg.descriptor)
	// A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler_config resource (e.g. doppler_config.backend_stg.descriptor)
	// +kubebuilder:validation:Optional
	Inherits []*string `json:"inherits,omitempty" tf:"inherits,omitempty"`

	// (String) The name of the Doppler project where the config is located
	// The name of the Doppler project where the config is located
	// +crossplane:generate:reference:type=github.com/oxlev/provider-doppler/apis/namespaced/secrets/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in secrets to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in secrets to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`
}

// ConfigSpec defines the desired state of Config
type ConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConfigInitParameters `json:"initProvider,omitempty"`
}

// ConfigStatus defines the observed state of Config.
type ConfigStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Config is the Schema for the Configs API. Manage a Doppler config.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,doppler}
type Config struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConfigSpec   `json:"spec"`
	Status            ConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConfigList contains a list of Configs
type ConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Config `json:"items"`
}

// Repository type metadata.
var (
	Config_Kind             = "Config"
	Config_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Config_Kind}.String()
	Config_KindAPIVersion   = Config_Kind + "." + CRDGroupVersion.String()
	Config_GroupVersionKind = CRDGroupVersion.WithKind(Config_Kind)
)

func init() {
	SchemeBuilder.Register(&Config{}, &ConfigList{})
}
