// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type EnvironmentInitParameters struct {

	// (String) The name of the Doppler environment
	// The name of the Doppler environment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether or not personal configs are enabled for the environment
	// Whether or not personal configs are enabled for the environment
	PersonalConfigs *bool `json:"personalConfigs,omitempty" tf:"personal_configs,omitempty"`
}

type EnvironmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the Doppler environment
	// The name of the Doppler environment
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether or not personal configs are enabled for the environment
	// Whether or not personal configs are enabled for the environment
	PersonalConfigs *bool `json:"personalConfigs,omitempty" tf:"personal_configs,omitempty"`

	// (String) The name of the Doppler project where the environment is located
	// The name of the Doppler project where the environment is located
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type EnvironmentParameters struct {

	// (String) The name of the Doppler environment
	// The name of the Doppler environment
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Whether or not personal configs are enabled for the environment
	// Whether or not personal configs are enabled for the environment
	// +kubebuilder:validation:Optional
	PersonalConfigs *bool `json:"personalConfigs,omitempty" tf:"personal_configs,omitempty"`

	// (String) The name of the Doppler project where the environment is located
	// The name of the Doppler project where the environment is located
	// +crossplane:generate:reference:type=github.com/oxlev/provider-doppler/apis/namespaced/secrets/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/oxlev/provider-doppler/internal/references.ReadyExternalName()
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in secrets to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in secrets to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`
}

// EnvironmentSpec defines the desired state of Environment
type EnvironmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            EnvironmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EnvironmentInitParameters `json:"initProvider,omitempty"`
}

// EnvironmentStatus defines the observed state of Environment.
type EnvironmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               EnvironmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Environment is the Schema for the Environments API. Manage a Doppler environment.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,doppler}
type Environment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EnvironmentSpec   `json:"spec"`
	Status EnvironmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnvironmentList contains a list of Environments
type EnvironmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Environment `json:"items"`
}

// Repository type metadata.
var (
	Environment_Kind             = "Environment"
	Environment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Environment_Kind}.String()
	Environment_KindAPIVersion   = Environment_Kind + "." + CRDGroupVersion.String()
	Environment_GroupVersionKind = CRDGroupVersion.WithKind(Environment_Kind)
)

func init() {
	SchemeBuilder.Register(&Environment{}, &EnvironmentList{})
}
