// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SecretInitParameters struct {

	// (String, Sensitive) The raw secret value
	// The raw secret value
	ValueSecretRef v2.LocalSecretKeySelector `json:"valueSecretRef" tf:"-"`

	// (String) The value type of the secret
	// The value type of the secret
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`

	// (String) The visibility of the secret. One of masked, unmasked, or restricted. Defaults to masked.
	// The visibility of the secret. One of `masked`, `unmasked`, or `restricted`. Defaults to `masked`.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type SecretObservation struct {

	// (String) The name of the Doppler config
	// The name of the Doppler config
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the Doppler project
	// The name of the Doppler project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// (String) The value type of the secret
	// The value type of the secret
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`

	// (String) The visibility of the secret. One of masked, unmasked, or restricted. Defaults to masked.
	// The visibility of the secret. One of `masked`, `unmasked`, or `restricted`. Defaults to `masked`.
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

type SecretParameters struct {

	// (String) The name of the Doppler config
	// The name of the Doppler config
	// +crossplane:generate:reference:type=github.com/oxlev/provider-doppler/apis/namespaced/secrets/v1alpha1.Config
	// +kubebuilder:validation:Optional
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// Reference to a Config in secrets to populate config.
	// +kubebuilder:validation:Optional
	ConfigRef *v2.NamespacedReference `json:"configRef,omitempty" tf:"-"`

	// Selector for a Config in secrets to populate config.
	// +kubebuilder:validation:Optional
	ConfigSelector *v2.NamespacedSelector `json:"configSelector,omitempty" tf:"-"`

	// (String) The name of the Doppler project
	// The name of the Doppler project
	// +crossplane:generate:reference:type=github.com/oxlev/provider-doppler/apis/namespaced/secrets/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in secrets to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v2.NamespacedReference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in secrets to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v2.NamespacedSelector `json:"projectSelector,omitempty" tf:"-"`

	// (String, Sensitive) The raw secret value
	// The raw secret value
	// +kubebuilder:validation:Optional
	ValueSecretRef v2.LocalSecretKeySelector `json:"valueSecretRef" tf:"-"`

	// (String) The value type of the secret
	// The value type of the secret
	// +kubebuilder:validation:Optional
	ValueType *string `json:"valueType,omitempty" tf:"value_type,omitempty"`

	// (String) The visibility of the secret. One of masked, unmasked, or restricted. Defaults to masked.
	// The visibility of the secret. One of `masked`, `unmasked`, or `restricted`. Defaults to `masked`.
	// +kubebuilder:validation:Optional
	Visibility *string `json:"visibility,omitempty" tf:"visibility,omitempty"`
}

// SecretSpec defines the desired state of Secret
type SecretSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            SecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SecretInitParameters `json:"initProvider,omitempty"`
}

// SecretStatus defines the observed state of Secret.
type SecretStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Secret is the Schema for the Secrets API. Manage a single Doppler secret in a config.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,doppler}
type Secret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.valueSecretRef)",message="spec.forProvider.valueSecretRef is a required parameter"
	Spec   SecretSpec   `json:"spec"`
	Status SecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretList contains a list of Secrets
type SecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Secret `json:"items"`
}

// Repository type metadata.
var (
	Secret_Kind             = "Secret"
	Secret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Secret_Kind}.String()
	Secret_KindAPIVersion   = Secret_Kind + "." + CRDGroupVersion.String()
	Secret_GroupVersionKind = CRDGroupVersion.WithKind(Secret_Kind)
)

func init() {
	SchemeBuilder.Register(&Secret{}, &SecretList{})
}
