apiVersion: secrets.doppler.m.crossplane.io/v1alpha1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: secrets/v1alpha1/environment
  labels:
    testing.upbound.io/example-name: backend_ci
  name: backend-ci
  namespace: upbound-system
spec:
  forProvider:
    name: Continuous Integration
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
