apiVersion: secrets.doppler.crossplane.io/v1alpha1
kind: Config
metadata:
  annotations:
    meta.upbound.io/example-id: secrets/v1alpha1/config
  labels:
    testing.upbound.io/example-name: backend_ci_github
  name: backend-ci-github
spec:
  forProvider:
    environmentSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
