apiVersion: secrets.doppler.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: secrets/v1alpha1/project
  labels:
    testing.upbound.io/example-name: backend
  name: backend
spec:
  forProvider:
    description: The main backend project
    name: backend
