apiVersion: secrets.doppler.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: secrets/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: db_password
  name: db-password
spec:
  forProvider:
    configSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    valueSecretRef:
      key: attribute.result
      name: example-password
      namespace: upbound-system
